import React from "react";
import { LegalLayout } from "../components/legal/LegalLayout";
import { BUSINESS_CONFIG } from "../../config/business";
import { ShieldAlert, AlertTriangle, Scale, Lock, Info } from "lucide-react";
import { Link } from "react-router";

export function TermsPage() {
  return (
    <LegalLayout
      title="Terms & Conditions"
      subtitle="Standard terms and conditions governing the access, licensing, and ethical usage of the CrackFlow SaaS platform and desktop AI interview assistant."
      badge="Legal Contract"
      lastUpdated="October 2026"
    >
      <div className="space-y-10 text-xs md:text-sm text-[#171A1F] leading-relaxed">
        {/* Important Warning Banner */}
        <div className="p-5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-950 space-y-2">
          <div className="flex items-center gap-2 font-bold text-amber-900 text-sm">
            <ShieldAlert size={18} />
            <span>Important Notice Regarding Permitted & Ethical Usage</span>
          </div>
          <p className="leading-relaxed">
            CrackFlow is designed as an assistive productivity tool for candidates. You are solely responsible for ensuring that your use of real-time audio capture, speech transcription, screen analysis, and AI assistance complies with all applicable recording laws (including wiretapping/consent laws) and with the specific rules, codes of conduct, exam policies, or employment agreements of your interviewers, employers, academic institutions, and assessment platforms. CrackFlow does not authorize or condone any unlawful, deceptive, or unethical usage.
          </p>
        </div>

        {/* Section 1: Introduction */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            1. Introduction
          </h2>
          <p className="text-[#59616D]">
            These Terms & Conditions ("Terms", "Agreement") constitute a legally binding agreement between you (the "User", "you") and the operator of CrackFlow ({BUSINESS_CONFIG.legalBusinessName}, "CrackFlow", "we", "us", or "our"), governing your access to and use of the website located at{" "}
            <a href={BUSINESS_CONFIG.websiteUrl} className="text-blue-600 underline">
              {BUSINESS_CONFIG.websiteUrl}
            </a>{" "}
            (the "Site"), our web-based customer dashboard, and our native desktop software application (collectively, the "Services").
          </p>
          <p className="text-[#59616D]">
            By creating an account, downloading the desktop client, purchasing a subscription, or continuing to browse our Services, you explicitly represent that you have read, understood, and agreed to be bound by these Terms. If you do not agree, you must immediately discontinue use of the Services.
          </p>
        </section>

        {/* Section 2: Definitions */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            2. Definitions
          </h2>
          <ul className="list-disc pl-5 space-y-1.5 text-[#59616D]">
            <li><strong>"Account":</strong> A registered user profile authenticated via our authentication provider (Google Firebase Auth).</li>
            <li><strong>"Desktop Client":</strong> The downloadable Windows executable software provided to active subscribers for live interview assistance and overlay rendering.</li>
            <li><strong>"Entitlement":</strong> An active license record stored in our backend establishing a user's right to execute AI queries and transcription sessions.</li>
            <li><strong>"AI Output":</strong> Real-time suggestions, code snippets, algorithm explanations, or textual hints generated by artificial intelligence models.</li>
            <li><strong>"Session Data":</strong> Audio streams, text transcripts, and user-provided context documents (resumes and job descriptions) processed during an interview session.</li>
          </ul>
        </section>

        {/* Section 3: Eligibility */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            3. Eligibility
          </h2>
          <p className="text-[#59616D]">
            You must be at least 18 years of age and possess full legal capacity to enter into binding agreements to register for and use CrackFlow. The Services are not intended for use by minors or individuals barred from receiving SaaS services under applicable national or international laws.
          </p>
        </section>

        {/* Section 4: Account Registration & Security */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            4. Account Registration & Security
          </h2>
          <p className="text-[#59616D]">
            To access paid features and download the Desktop Client, you must register for an Account using a valid email address and secure password. You are strictly responsible for maintaining the confidentiality of your login credentials.
          </p>
          <p className="text-[#59616D]">
            <strong>One Person Per Account:</strong> Each CrackFlow account and desktop license is strictly individual. You may not share, sell, rent, lease, sub-license, or transfer your login credentials or session tokens to any third party. We employ automated token and concurrency controls to prevent multi-device account sharing.
          </p>
        </section>

        {/* Section 5: CrackFlow Services */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            5. CrackFlow Services Description
          </h2>
          <p className="text-[#59616D]">
            CrackFlow provides real-time speech transcription, context-grounded AI suggestions, and transparent desktop overlay displays during conversational technical assessments. The Services are delivered over the Internet and require an active broadband network connection, functional microphone input, and a compatible Windows operating system.
          </p>
        </section>

        {/* Section 6: Desktop Application */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            6. Desktop Application License & System Requirements
          </h2>
          <p className="text-[#59616D]">
            Subject to continuous compliance with these Terms and an active Entitlement, CrackFlow grants you a revocable, non-exclusive, non-transferable, non-sublicensable personal license to install and execute the Desktop Client on a single compatible device running Windows 10 or Windows 11 (64-bit).
          </p>
          <p className="text-[#59616D]">
            You agree not to reverse engineer, decompile, disassemble, modify, create derivative works from, or bypass hardware exclusion protections embedded in the Desktop Client.
          </p>
        </section>

        {/* Section 7: Subscription Plans */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            7. Subscription Plans
          </h2>
          <p className="text-[#59616D]">
            We offer tiered recurring subscription plans (such as Starter at ₹499/month and Pro at ₹999/month). Feature allowances, concurrent request caps, and cloud priority tiers for each plan are detailed on our{" "}
            <Link to="/pricing" className="text-blue-600 underline font-semibold">
              Pricing Page
            </Link>
            .
          </p>
        </section>

        {/* Section 8: Lifetime Plan */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            8. Lifetime Plan Terms
          </h2>
          <p className="text-[#59616D]">
            The CrackFlow Lifetime Pass (₹4999) is a one-time payment providing hosted access to Pro features for the commercial operational lifespan of the CrackFlow service offering without recurring monthly fees.
          </p>
          <p className="text-[#59616D]">
            "Lifetime" refers to the lifetime of the service offering, not the biological lifetime of the customer or an indefinite corporate warranty. If CrackFlow materially modifies the architecture or discontinues the service, reasonable advance notice will be provided. Lifetime accounts remain subject to fair use limits to prevent malicious automated utilization.
          </p>
        </section>

        {/* Section 9: Pricing & Payments */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            9. Pricing and Payments
          </h2>
          <p className="text-[#59616D]">
            All prices are stated in Indian Rupees (INR). Payments are processed through authorized payment gateway partners (such as {BUSINESS_CONFIG.paymentProviderName}). By submitting payment information, you authorize our payment processor to charge the specified amount to your chosen payment method.
          </p>
          <p className="text-[#59616D]">
            CrackFlow does not directly store, process, or view your full credit card number, debit card number, or CVV/CVC security codes; all sensitive cardholder transmission is handled directly by the payment gateway under strict PCI-DSS standards.
          </p>
        </section>

        {/* Section 10: Billing & Renewal */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            10. Billing and Renewal
          </h2>
          <p className="text-[#59616D]">
            Monthly subscriptions automatically renew at the beginning of each 30-day billing cycle unless canceled prior to the renewal date. You will be billed using the payment method on file. If an automated renewal charge fails, your paid Entitlement will be suspended until successful settlement.
          </p>
        </section>

        {/* Section 11: Cancellation */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            11. Cancellation
          </h2>
          <p className="text-[#59616D]">
            You may cancel your subscription at any time directly through your web account dashboard or by contacting customer support. Cancellation halts future automatic recurring charges. Upon cancellation, your access remains active through the remainder of the currently paid billing period.
          </p>
        </section>

        {/* Section 12: Refunds */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            12. Refunds
          </h2>
          <p className="text-[#59616D]">
            Refunds are evaluated strictly under our{" "}
            <Link to="/refund-policy" className="text-blue-600 underline font-semibold">
              Refund & Cancellation Policy
            </Link>
            . Because CrackFlow delivers immediate digital software and cloud compute resources, purchases where the service has been actively utilized (e.g., initiating live transcription or AI generation sessions) are generally non-refundable, except where required by applicable consumer law.
          </p>
        </section>

        {/* Section 13: Digital Delivery */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            13. Digital Delivery
          </h2>
          <p className="text-[#59616D]">
            CrackFlow is delivered digitally as described in our{" "}
            <Link to="/shipping-policy" className="text-blue-600 underline font-semibold">
              Digital Delivery Policy
            </Link>
            . No physical shipments are dispatched. Entitlement is provisioned electronically upon payment verification.
          </p>
        </section>

        {/* Section 14: Acceptable Use */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            14. Acceptable Use Policy
          </h2>
          <p className="text-[#59616D]">
            You agree not to use CrackFlow to:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-[#59616D]">
            <li>Engage in any illegal, fraudulent, or deceptive activities.</li>
            <li>Violate intellectual property rights, non-disclosure agreements (NDAs), or trade secrets.</li>
            <li>Transmit viruses, malware, or exploit scripts against our servers, cloud backend, or APIs.</li>
            <li>Scrape, spider, or reverse engineer any part of the service.</li>
            <li>Bypass rate limits, licensing checks, or user concurrency restrictions.</li>
          </ul>
        </section>

        {/* Section 15: User Responsibilities */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            15. User Responsibilities & Third-Party Rules
          </h2>
          <p className="text-[#59616D]">
            <strong className="text-[#171A1F]">Critical Compliance Requirement:</strong> You acknowledge and agree that you are solely responsible for verifying that your use of real-time audio capture, transcription, and AI assistance complies with all contractual, ethical, academic, and statutory rules governing your interactions.
          </p>
          <p className="text-[#59616D]">
            CrackFlow does not grant you permission to violate the terms of service of third-party platforms (including Zoom, Google Meet, Microsoft Teams, HackerRank, LeetCode, or CodeSignal), employer codes of conduct, or proctoring regulations. Where two-party or all-party consent is mandated by local audio recording or wiretapping laws, you are solely responsible for providing notice and obtaining lawful consent.
          </p>
        </section>

        {/* Section 16: AI-Generated Content */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            16. AI-Generated Content & Disclaimers
          </h2>
          <p className="text-[#59616D]">
            AI outputs are synthesized through automated artificial intelligence and machine learning models. Artificial intelligence systems may generate inaccurate, incomplete, hallucinated, or contextually unsuitable information.
          </p>
          <p className="text-[#59616D]">
            CrackFlow makes no warranty regarding the correctness or completeness of AI Output. You are solely responsible for evaluating, verifying, and deciding whether to adopt or express any answer or code suggestion.{" "}
            <strong className="text-[#171A1F]">CrackFlow does not guarantee interview success, job offers, employment retention, or any particular professional outcome.</strong>
          </p>
        </section>

        {/* Section 17: Audio, Microphone and Screen Data */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            17. Audio, Microphone and Screen Data
          </h2>
          <p className="text-[#59616D]">
            CrackFlow accesses audio devices and displays solely upon your direct, explicit user activation inside the Desktop Client. Audio chunks are streamed in real time to our speech-to-text processing infrastructure for immediate transcription. Audio streams are not permanently archived on our servers once transcription is rendered.
          </p>
        </section>

        {/* Section 18: Third-Party Services */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            18. Third-Party Service Providers
          </h2>
          <p className="text-[#59616D]">
            CrackFlow utilizes proven enterprise cloud infrastructure partners to deliver the Services (including managed authentication, speech-to-text processing, natural language generation models, and authorized payment gateways like {BUSINESS_CONFIG.paymentProviderName}). Your use of the Services is subject to the technical availability of these providers.
          </p>
        </section>

        {/* Section 19: Intellectual Property */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            19. Intellectual Property
          </h2>
          <p className="text-[#59616D]">
            All rights, title, and interest in CrackFlow, including source code, UI designs, desktop binaries, branding, logos, and documentation, are the exclusive intellectual property of {BUSINESS_CONFIG.legalBusinessName}. Nothing in these Terms grants you ownership rights in the Services.
          </p>
        </section>

        {/* Section 20: Service Availability */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            20. Service Availability & Maintenance
          </h2>
          <p className="text-[#59616D]">
            We endeavor to maintain high platform availability; however, we do not guarantee uninterrupted or error-free operation. We reserve the right to perform scheduled maintenance, update APIs, or modify backend infrastructure without liability.
          </p>
        </section>

        {/* Section 21: Security */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            21. Security
          </h2>
          <p className="text-[#59616D]">
            We implement administrative and technical security measures (including TLS 1.3 transport encryption and short-lived authorization tokens). However, no internet transmission is 100% immune from security breaches. You are responsible for securing your workstation and local network.
          </p>
        </section>

        {/* Section 22: Account Suspension/Termination */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            22. Account Suspension & Termination
          </h2>
          <p className="text-[#59616D]">
            We reserve the right to immediately suspend or permanently terminate your Account without notice if we detect fraudulent activity, payment disputes or chargebacks, license sharing, reverse engineering, or material breach of these Terms.
          </p>
        </section>

        {/* Section 23: Disclaimer */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            23. Disclaimer of Warranties
          </h2>
          <p className="text-[#59616D] uppercase text-[11px] leading-relaxed">
            THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT CRACKFLOW WILL MEET YOUR SPECIFIC INTERVIEW REQUIREMENTS OR OPERATE WITHOUT INTERRUPTION.
          </p>
        </section>

        {/* Section 24: Limitation of Liability */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            24. Limitation of Liability
          </h2>
          <p className="text-[#59616D] uppercase text-[11px] leading-relaxed">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL CRACKFLOW, ITS DIRECTORS, EMPLOYEES, OR PARTNERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, USE, GOODWILL, OR LOSS OF EMPLOYMENT OPPORTUNITY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES. OUR TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO CRACKFLOW IN THE THREE (3) MONTHS PRECEDING THE CLAIM.
          </p>
        </section>

        {/* Section 25: Changes to Services */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            25. Changes to Services
          </h2>
          <p className="text-[#59616D]">
            We may introduce new features, retire outdated features, or modify application limits from time to time to enhance system performance and security.
          </p>
        </section>

        {/* Section 26: Changes to Terms */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            26. Changes to Terms
          </h2>
          <p className="text-[#59616D]">
            We reserve the right to revise these Terms periodically. Updates will be reflected by amending the "Last Updated" date at the top of this page. Continued use of CrackFlow following notice of revisions constitutes binding acceptance of modified terms.
          </p>
        </section>

        {/* Section 27: Governing Law */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            27. Governing Law
          </h2>
          <p className="text-[#59616D]">
            These Terms and any dispute arising out of or related to them shall be governed by and construed in accordance with the substantive laws applicable to {BUSINESS_CONFIG.legalBusinessName}, without regard to conflict of law principles.
          </p>
        </section>

        {/* Section 28: Dispute Resolution */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            28. Dispute Resolution
          </h2>
          <p className="text-[#59616D]">
            In the event of any controversy, claim, or dispute, the parties agree to first attempt informal resolution by submitting a written notice to{" "}
            <a href={`mailto:${BUSINESS_CONFIG.supportEmail}`} className="text-blue-600 underline font-mono">
              {BUSINESS_CONFIG.supportEmail}
            </a>
            . If informal discussions fail within 30 calendar days, the dispute shall be resolved through final and binding arbitration or competent courts having jurisdiction.
          </p>
        </section>

        {/* Section 29: Contact Information */}
        <section className="space-y-3">
          <h2 className="text-base md:text-lg font-bold text-[#171A1F] border-b pb-1.5 border-[#E5E7EB]">
            29. Contact Information
          </h2>
          <p className="text-[#59616D]">
            For questions, legal notices, or inquiries regarding these Terms & Conditions, please contact us at:
          </p>
          <div className="p-4 rounded-xl border border-[#E5E7EB] bg-[#FAFAF8] space-y-1 font-mono text-xs">
            <div><strong>Operator:</strong> {BUSINESS_CONFIG.legalBusinessName}</div>
            <div><strong>Email:</strong> {BUSINESS_CONFIG.supportEmail}</div>
            <div><strong>Address:</strong> {BUSINESS_CONFIG.registeredAddress}</div>
            <div><strong>Website:</strong> {BUSINESS_CONFIG.websiteUrl}</div>
          </div>
        </section>
      </div>
    </LegalLayout>
  );
}
